#' A 'ggplot2' geom to draw blunt restriction sites
#'
#' `geom_blunt_restriction_site()` draws a geom representing a blunt
#' restriction site, the site at which a particular restriction enzyme cleaves
#' without leaving any overhanging nucleotides.
#'
#' The blunt restriction site is drawn as a pair of straight brackets facing
#' away from one another, with the site location centered between the brackets.
#'
#' The position of the restriction site on the molecular backbone is set with
#' the `x` aesthetic. The molecular backbone that it is associated with is set
#' with the `y` aesthetic. This geom does not accept a `forward` aesthetic, as
#' it is not associated with a particular strand.
#'
#' @section Aesthetics:
#'
#' - x (required; position of the restriction site)
#' - y (required; the molecular backbone)
#' - alpha
#' - colour
#' - linetype
#' - size
#'
#' @param mapping,data,stat,position,na.rm,show.legend,inherit.aes,... As
#' standard for ggplot2. inherit.aes is set to FALSE by default.
#' @param height `grid::unit()` opbject giving the height of the restriction
#' site above the molecular backbone. Defaults to 5 mm.
#'
#' @examples
#'
#' ggplot2::ggplot(feature_garden[feature_garden$feature == 
#'                                "blunt restriction site", ],
#'                 ggplot2::aes(x = start, y = molecule)) +
#'   geom_blunt_restriction_site(inherit.aes = TRUE)
#'
#' @seealso [geom_blunt_restriction_site_label()]
#'
#' @export
geom_blunt_restriction_site <- function(
  mapping = NULL,
  data = NULL,
  stat = "identity",
  position = "identity",
  na.rm = FALSE,
  show.legend = NA,
  inherit.aes = FALSE,
  height = grid::unit(5, "mm"),
  ...
) {
  ggplot2::layer(
    geom = GeomBluntRestrictionSite,
    mapping = mapping,
    data = data,
    stat = stat,
    position = position,
    show.legend = show.legend,
    inherit.aes = inherit.aes,
    params = list(
      na.rm = na.rm,
      height = height,
      ...
    ) 
  )
}

#' GeomBluntRestrictionSite
#' @noRd
GeomBluntRestrictionSite <- ggplot2::ggproto("GeomBluntRestrictionSite", ggplot2::Geom,
  required_aes = c("x", "y"),
  default_aes = ggplot2::aes(
    alpha = 1,
    colour = "black",
    linetype = 1,
    size = 1
  ),

  draw_key = ggplot2::draw_key_abline,

  setup_data = function(data, params) {
    data
  },

  setup_params = function(data, params) {

    # Height should not be negative
    if (as.numeric(params$height) < 0) {
      cli::cli_abort("{.arg height} argument to {.fun geom_blunt_restriction_site} cannot be negative") 
    }

    params
  },

  draw_panel = function(data, panel_scales, coord, height) {

    # Detect coordinate system and transform values
    coord_system <- get_coord_system(coord)
    data <- data_to_grid(data, coord_system, panel_scales, coord)

    gt <- grid::gTree(
      data = data,
      cl = "bluntrestrictionsitetree",
      height = height,
      coord_system = coord_system
    )
    gt$name <- grid::grobName(gt, "geom_blunt_restriction_site")
    gt
  }
)

#' @importFrom grid makeContent
#' @export
makeContent.bluntrestrictionsitetree <- function(x) {

  data <- x$data

  # Prepare grob for each restriction site
  grobs <- lapply(seq_len(nrow(data)), function(i) {

    restriction_site <- data[i, ]

    # Set up geometry
    r <- ifelse(x$coord_system == "polar", restriction_site$away, NA)
    awayness <- unit_to_alaw(x$height, "away", x$coord_system, r) 
    alongness <- unit_to_alaw(x$height, "along", x$coord_system, r)

    # Generate the polyline. blunt_restriction_site_alongs and
    # blunt_restriction_site_aways are internal data generated by
    # data-raw/prepare_coordinates.R
    alongs <- restriction_site$along + (alongness * 
                                        blunt_restriction_site_alongs)
    aways <- restriction_site$away + (awayness * 
                                      blunt_restriction_site_aways)
    ids <- blunt_restriction_site_indices

    # If in polar coordinates, segment the polyline
    if (x$coord_system == "polar") {
      segmented <- segment_polarline(alongs, aways, ids = ids)
      alongs <- segmented$thetas
      aways <- segmented$rs
      ids <- segmented$ids
    }

    # Convert polygon into Cartesian coordinates within the grid viewport
    coords <- alaw_to_grid(alongs, aways, x$coord_system, r)

    # Generate polygon grob for the restriction site
    pg <- grid::polylineGrob(
      x = coords$x,
      y = coords$y,
      id = ids,
      gp = grid::gpar(
        col = restriction_site$colour,
        lty = restriction_site$linetype,
        lwd = restriction_site$size
      )
    )

    # Return the grob
    pg
  })

  class(grobs) <- "gList"
  grid::setChildren(x, grobs)
}
